# Generated by Django 5.0.1 on 2024-01-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforhealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
